export const ROUTES = {
  HOME: 'HOME',
  TODOS: 'TODOS',
  TODO: 'TODO',
  USERS: 'USERS',
  ADD_TODO: 'ADD_TODO'
};

export const TODOS = {
  ADD_REQ: 'TODOS_ADD_REQ',
  ADD_RES: 'TODOS_ADD_RES',
  LOAD: 'TODOS_LOAD',
  SUCCESS: 'TODOS_SUCCESS',
  FAIL: 'TODOS_FAIL',
  UPDATE_REQ: 'TODOS_UPDATE_REQ',
  UPDATE_RES: 'TODOS_UPDATE_RES'
};

export const USERS = {
  LOAD: 'USERS_LOAD',
  SUCCESS: 'USERS_SUCCESS',
  FAIL: 'USERS_FAIL',
  CHANGE_CURRENT_USER: 'CHANGE_CURRENT_USER'
};